# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html

http.host: 0.0.0.0
http.port: 5066

filebeat.autodiscover:
  providers:
    - type: docker
      hints:
        enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: oncall-web
          config:
            # input goes here
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                - dissect:
                    tokenizer: "%{ipishka} - - [%{datetishka}] %{method} %{path} %{protocol} %{status_code} %{size} %{referer} %{user_agent}"
                    target_prefix: extra
                    trim_values: all

        # todo: add mysql later

output.logstash:
  enabled: true
  hosts:
    - logstash:5044
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}
